name: Auto Blog Drafter

on:
  schedule:
    - cron: "*/20 * * * *"  # runs every 6 hours

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install libraries
        run: |
          pip install requests google-api-python-client google-auth google-auth-oauthlib

      - name: Run script
        run: python main.py
